### ISSUE TITLE
Also send Channel name in message

### ISSUE THREAD

**Issue by Slevin90** [deadc0de6/weegram#1]
At this moment, the messages are only say what user send the message.
If you have multiple channels, it can be usefull to say

[Time] Message from "[username]" in [#Channel] on weechat

**Comment by deadc0de6** [comment]
I added the channel in the version in the branch [channel](https://github.com/deadc0de6/weegram/tree/channel) however I didn't get time to test it.

Let me know if both *private* and *highlight* message notifications work. Thanks!

**Comment by Slevin90** [comment]
Not yet..  in stead of channel it is showing my own nickname...
I believe weechat terminology could be buffer,  vs channel can give confusion?

**Comment by deadc0de6** [comment]
AFAIK it is currently not possible to retrieve the channel for highlighted messages using weechat API in python. Sorry for that but it's beyond my own control.
