### ISSUE TITLE
Broken since upgrade to weechat 2.7.1

### ISSUE THREAD

**Issue by Slevin90** [deadc0de6/weegram#2]

**Comment by Slevin90** [comment]
`1:06:00 weechat     | weegram status:
                     │21:06:00 weechat     | - enabled: on
                     │21:06:00 weechat     | python: stdout/stderr (weegram): Traceback (most recent call last):
                     │21:06:00 weechat     | python: stdout/stderr (weegram):   File "/home/slevin/.weechat/python/autoload/weegram.py", line 184, in
                     │                     | command_cb
                     │21:06:00 weechat     | python: stdout/stderr (weegram):     pstatus()
                     │21:06:00 weechat     | python: stdout/stderr (weegram):   File "/home/slevin/.weechat/python/autoload/weegram.py", line 115, in
                     │                     | pstatus
                     │21:06:00 weechat     | python: stdout/stderr (weegram):     out('- inactivity: {}'.format(get_cfg('timer')))
                     │21:06:00 weechat     | python: stdout/stderr (weegram):   File "/home/slevin/.weechat/python/autoload/weegram.py", line 96, in
                     │                     | get_cfg
                     │21:06:00 weechat     | python: stdout/stderr (weegram):     w.config_set_plugin(key, DEFAULTS[key])
                     │21:06:00 weechat     | python: stdout/stderr (weegram): KeyError: 'timer'
                     │21:06:00 weechat =!= | python: error in function "command_cb"`

**Comment by Slevin90** [comment]
Sorry, not broken

**Comment by deadc0de6** [comment]
I still fixed an issue with newer version of python (see https://github.com/deadc0de6/weegram/commit/8a81cb3dac3152012e2ca09847e06de09448a416) and tested weegram successfully with weechat 2.7.1.
